POSTGRES:
  POSTGRES_HOST: 139.198.165.102
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Z3tkxJVkPG
  POSTGRES_DATABASE: edu
  POSTGRES_PORT: 30000
  POSTGRES_SSL_MODE: disable
  POSTGRES_TIME_ZONE: Asia/Shanghai
